name: Manual workflow

on:
  push:
    branches: [master]

jobs:
  printenv:
    runs-on: windows-latest

    steps:
    - name: Print environment
      run: |
        Write-host "Print environment"
        $psversiontable
        get-computerinfo
