name: Default workflow

on:
  push:
    branches: [master]

jobs:
  printenv:
    runs-on: windows-latest

    steps:
    - name: Print environment
      run: |
        Write-host "Print environment"
        # $psversiontable
        Get-Computerinfo -property 'OsArchitecture','OsLocale','OsProductType','OsName','OsVersion','TimeZone' | Format-List
        Get-ChildItem env:*HOME* | Sort-Object Name
    - name: Print environment (cmd)
      shell: cmd
      run: |
        where curl.exe
        @echo Current directory: "%CD%"

  setenv:
    needs: printenv
    runs-on: windows-latest
    
    steps:
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.17
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Check environment setup
      run: |
        deno --version
        # https://deno.land/manual/getting_started/permissions#permissions-list
        deno run https://deno.land/std/examples/welcome.ts
        deno eval "console.log(Deno.version)"
        node --version

  portela-examples:
    needs: setenv
    runs-on: windows-latest
    # The default timeout for each task is 360 minutes.
    timeout-minutes: 2
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Chapter 1 examples
      shell: cmd
      run: |
        @echo "GITHUB_WORKSPACE=%GITHUB_WORKSPACE%"
        @echo "CWD=%CD%"
        type "%GITHUB_WORKSPACE%\portela-examples\Chapter01\http-server\http-server.bat"
