name: Default workflow

on:
  push:
    branches: [master]

jobs:
  printenv:
    runs-on: windows-latest

    steps:
    - name: Print environment
      run: |
        Write-host "Print environment"
        # $psversiontable
        Get-Computerinfo -property 'OsArchitecture','OsLocale','OsProductType','OsName','OsVersion','TimeZone' | Format-List
        Get-ChildItem env:*HOME* | Sort-Object Name
    - name: Print environment (cmd)
      shell: cmd
      run: |
        where curl.exe

  setenv:
    needs: printenv
    runs-on: windows-latest
    
    steps:
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.17
    - name: Print Deno version
      run: |
        deno --version
        # https://deno.land/manual/getting_started/permissions#permissions-list
        deno run https://deno.land/std/examples/welcome.ts
        deno eval "console.log(Deno.version)"

  portela-examples:
    needs: setenv
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Chapter 1 examples
      shell: cmd
      run: |
        dir "Chapter01\http-server\http-server.bat"
